# -*- coding: utf-8 -*-
"""predictive_analysis.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1vBW91JXfz1ryCSMpZNe3ETBZ09RSFZBg
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score

df = pd.read_csv("stock_price_dataset.csv")

print("First 5 rows of dataset:")
print(df.head())

print("\nDataset Information:")
print(df.info())

print("\nStatistical Summary:")
print(df.describe())

print("\nMissing Values:")
print(df.isnull().sum())

df['Date'] = pd.to_datetime(df['Date'])

print("\nDataset after converting Date column:")
print(df.head())

df['Day'] = np.arange(1, len(df) + 1)

print("\nDataset with Day column:")
print(df.head())

plt.figure(figsize=(10, 5))
plt.plot(df['Date'], df['Close'], marker='o')
plt.title("Historical Stock Closing Price")
plt.xlabel("Date")
plt.ylabel("Closing Price")
plt.grid(True)
plt.show()

X = df[['Day']]
y = df['Close']

model = LinearRegression()
model.fit(X, y)

df['Predicted_Close'] = model.predict(X)

print("\nActual and Predicted Closing Prices:")
print(df[['Date', 'Close', 'Predicted_Close']].head())

mae = mean_absolute_error(y, df['Predicted_Close'])
mse = mean_squared_error(y, df['Predicted_Close'])
rmse = np.sqrt(mse)
r2 = r2_score(y, df['Predicted_Close'])

print("\nModel Evaluation Results:")
print("Mean Absolute Error:", mae)
print("Mean Squared Error:", mse)
print("Root Mean Squared Error:", rmse)
print("R2 Score:", r2)

future_days = np.arange(len(df) + 1, len(df) + 8).reshape(-1, 1)

future_predictions = model.predict(future_days)

future_dates = pd.date_range(
    start=df['Date'].iloc[-1] + pd.Timedelta(days=1),
    periods=7
)

future_df = pd.DataFrame({
    'Date': future_dates,
    'Predicted_Close': future_predictions
})

print("\nFuture Stock Price Forecast:")
print(future_df)

plt.figure(figsize=(12, 6))

plt.plot(df['Date'], df['Close'], label='Actual Closing Price', marker='o')
plt.plot(df['Date'], df['Predicted_Close'], label='Predicted Closing Price', marker='x')
plt.plot(
    future_df['Date'],
    future_df['Predicted_Close'],
    label='Future Forecast',
    marker='s',
    linestyle='--'
)

plt.title("Stock Price Prediction Using Historical Data")
plt.xlabel("Date")
plt.ylabel("Closing Price")
plt.legend()
plt.grid(True)
plt.show()

future_df.to_csv("future_stock_price_forecast.csv", index=False)
df.to_csv("stock_price_with_predictions.csv", index=False)

print("\nOutput files saved successfully:")
print("1. future_stock_price_forecast.csv")
print("2. stock_price_with_predictions.csv")

import pandas as pd

# Select actual and predicted stock price data
actual_predicted = df[['Date', 'Open', 'High', 'Low', 'Close', 'Volume', 'Predicted_Close']].copy()

# Rename columns for clarity
actual_predicted.rename(columns={
    'Close': 'Actual_Close'
}, inplace=True)

# Add type column
actual_predicted['Data_Type'] = 'Historical Prediction'

# Prepare future forecast data
future_output = future_df.copy()

# Add missing columns to match historical data
future_output['Open'] = None
future_output['High'] = None
future_output['Low'] = None
future_output['Volume'] = None
future_output['Actual_Close'] = None
future_output['Data_Type'] = 'Future Forecast'

# Rename future prediction column
future_output.rename(columns={
    'Predicted_Close': 'Predicted_Close'
}, inplace=True)

# Arrange columns
future_output = future_output[
    ['Date', 'Open', 'High', 'Low', 'Actual_Close', 'Volume', 'Predicted_Close', 'Data_Type']
]

actual_predicted = actual_predicted[
    ['Date', 'Open', 'High', 'Low', 'Actual_Close', 'Volume', 'Predicted_Close', 'Data_Type']
]

# Combine both historical predictions and future forecast
final_output = pd.concat([actual_predicted, future_output], ignore_index=True)

# Save everything into one CSV file
final_output.to_csv("complete_stock_prediction_output.csv", index=False)

print("Complete output saved as complete_stock_prediction_output.csv")